# docker-compose-linux.yml
# docker-compose --file docker-compose-linux.yml up
version: '3'
services:
  jupyter-ros:
    image: intel4coro/base-notebook:20.04-noetic
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports: 
      - 8888:8888
    # user: root
    user: jovyan
    working_dir: /home/jovyan
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    entrypoint: ["/home/jovyan/work/entrypoint.sh"]
    volumes:
      - ./:/home/jovyan/work
    environment:
      - DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
